spring.application.name=job-radar

jobradar.ingestion.schedule.enabled=false
jobradar.ingestion.schedule.page=1
jobradar.ingestion.schedule.fixed-delay=PT1H
jobradar.ingestion.schedule.initial-delay=PT30S
