ALTER TABLE job_postings
    ADD COLUMN description TEXT NOT NULL DEFAULT '',
    ADD COLUMN tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    ADD COLUMN job_types TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
